### ISSUE TITLE
Hide "uploader" filter from users

### ISSUE THREAD

**Issue by vykozlov** [EOSC-synergy/eosc-perf#103]
**Is your feature request related to a problem? Please describe.**
Yes, we want to hide "Uploader" filter in order not to share emails (private info) of other people.

**Describe the solution you'd like**
"Uploader" filter is only available to admins

**Alternative solution**
There is no "Uploader" filter at all.

**Comment by TheChristophe** [comment]
I have implemented the `"Uploader" filter is only available to admins` route, the filter is now available & useable for administrators.
