### ISSUE TITLE
Sometimes "Linear" and "Logarithmic" graph types are not accessible (grayed out)

### ISSUE THREAD

**Issue by vykozlov** [EOSC-synergy/eosc-perf#109]
**Describe the bug**
Sometime "Linear" and "Logarithmic" graph types are not accessible (grayed out).

**To Reproduce**
1. Access perf.test.fedcloud.eu
2. Choose e.g. deephdc/deep-oc-benchmarks_cnn:benchmark
3. Sort the table by flavor
4. Select first 4 entries (2 from ifca-lcg2, 2 from ForHLR2) (btw, the diagram is plotted with already first entry selected)
5. X-Axis = training.num_gpus, Y-axis=training.score
6. Try to change the diagram type, neither "linear" nor "logarithmic" is accessible

**Expected behavior**
One can switch to "linear" or "logarithmic", apply "Group by site"

**Screenshots**
![diagram-no_linear_log](https://user-images.githubusercontent.com/8523545/112472136-13519f00-8d6d-11eb-9179-70dc16131a68.jpg)

**Additional context**
HOWEVER, If one goes first to the "Result" page and then selects the benchmark,  and goest through items 2-5) above:
a) diagram is not plotted with an entry selected, one has to select Diagram type "Line graph" for plotting (probably better this way)
b) switching to "linear" and "logarithmic" **is** available, as well as "Group by site"

**Comment by TheChristophe** [comment]
I believe to have fixed the issue; it was not updating if the results were from different sites (why that check was there? I don't know/remember). Using the reproduction steps, it now works. Let me know if you can still somehow reproduce the issue.

**Comment by vykozlov** [comment]
So far, I do not experience the problem anymore. Let's consider as resolved and close it.
