### ISSUE TITLE
Enable cookie authentication on backend

### ISSUE THREAD

**Issue by BorjaEst** [EOSC-synergy/eosc-perf#120]
**Is your feature request related to a problem? Please describe.**
Authentication to backend through oidc-token might be slow due to a continous call to the introspection endpoint to check the validity of the token. In the case of frontend usage, it might impact on the navigation "speed". To solve this it might be better to provide as well a cookies authentication so once the user is identified once (for example through log-in in the frontend), a cookie might be used to avoid the "instrospection" call.

**Describe the solution you'd like**
Allow the usage of authentication via cookies.

**Describe alternatives you've considered**
 - Do not call introspection always, trust the intern token expiration value
 - On frontend, save the token into an ecrypted cookie when the user logs-in

**Comment by BorjaEst** [comment]
Planned on #908735712e37b0863cb1715ad4125bdb20055dcc
No by backend, but frontend should be able to get tokens

**Comment by TheChristophe** [comment]
Closed as this has been made redundant / been replaced by pure frontend authentication
