### ISSUE TITLE
Error while loading results

### ISSUE THREAD

**Issue by vykozlov** [EOSC-synergy/eosc-perf#124]
**Describe the bug**
Want to create a plot, but after selecting the Benchmark, all results are gone and error "Error while loading results" is shown.

**To Reproduce**
1. Go to https://perf.test.fedcloud.eu/
2. Click on "Benchmark" -> Select
3. Select "thechristophe/openbench-c-ray:latest"
3. See error

**Additional context**
Tested in:
Chrome Version 93.0.4577.63 (Official Build) (64-bit), Linux
Firefox 92.0 (64-bit), Linux

**Comment by TheChristophe** [comment]
The commit was supposed to close the issue but github doesnt want to so I'm doing it manually
