### ISSUE TITLE
Result reports/claim message not intuitive

### ISSUE THREAD

**Issue by BorjaEst** [EOSC-synergy/eosc-perf#125]
**Is your feature request related to a problem? Please describe.**
When you report/claim a result, the message field is at the bottom, the user has to scroll a lot in long results and it is not intuitive for new users they can claim reports.

**Describe the solution you'd like**
The claim message input field should be next to the submit button.

**Comment by TheChristophe** [comment]
Moved message field above JSON preview instead of next to the submit button due to implementation details
