### ISSUE TITLE
Add cookie banner & google analytics

### ISSUE THREAD

**Issue by vykozlov** [EOSC-synergy/eosc-perf#126]
Purpose: to be compliant with GDPR

What about https://www.cookieconsent.com/ ?

Used now at:
*  https://appsgrycap.i3m.upv.es:31443/im-dashboard/login
*  https://o3as.data.kit.edu/

**Comment by TheChristophe** [comment]
Pending in #139

**Comment by TheChristophe** [comment]
Closing due to decision not to use google analytics
