### ISSUE TITLE
IOController Overhaul

### ISSUE THREAD

**Issue by mlbehr** [EOSC-synergy/eosc-perf#13]
There are still some issues with functionality (e.g adding of sites) and typos in here.

**Comment by TheChristophe** [comment]
controller._valid_docker_hub_name should be rewritten not to use some weird page fetching and parsing thing but instead use the (albeit undocumented) dockerhub api, refer to the benchmark review page for an example

**Comment by TheChristophe** [comment]
controller.get_unapproved_sites is currently not functional - it should probably either be disabled or removed given we have no review list page

**Comment by mlbehr** [comment]
I removed many typos in 3c16cd1 and fixed site submission and report processing. controller._valid_docker_hub_name must still be rewritten according to Christophe's comment.

**Comment by mlbehr** [comment]
But as the overhaul is mostly finished, I'll close this issue now and create a new one for the docker name stuff.
