### ISSUE TITLE
Result execution datetime accept inputs in the future

### ISSUE THREAD

**Issue by BorjaEst** [EOSC-synergy/eosc-perf#130]
**Describe the bug**
Execution date input parameter accepts dates in the future

**Comment by TheChristophe** [comment]
TODO: prevent users from selecting future dates in frontend as well

**Comment by TheChristophe** [comment]
Resolved for the frontend in 957f6af6fb4761e2093ac0d349d5d54debbd3498

**Comment by TheChristophe** [comment]
Resolved for the frontend in 957f6af6fb4761e2093ac0d349d5d54debbd3498
