### ISSUE TITLE
Check dependabot alert about "path-parse"

### ISSUE THREAD

**Issue by vykozlov** [EOSC-synergy/eosc-perf#134]
Details:

https://github.com/EOSC-synergy/eosc-perf/security/dependabot/frontend_client/package-lock.json/path-parse/open

**Comment by TheChristophe** [comment]
The link is dead

**Comment by vykozlov** [comment]
you have to login to github to see it.
but the alert seems to be for the "master" branch, i.e. might be not relevant, please, check

**Comment by vykozlov** [comment]
that one : https://github.com/EOSC-synergy/eosc-perf/security/dependabot  ?
