### ISSUE TITLE
Change benchmark does not reset the graph

### ISSUE THREAD

**Issue by BorjaEst** [EOSC-synergy/eosc-perf#135]
**Describe the bug**
If after visualizing one benchmark graph/results I decicde to change, then for the new selected benchmark I have issues:
 - All results are selected
 - The graph correspond to the previous results (not the new ones)
 - Even unselecting the results, the graph does not chnge

**To Reproduce**
1. Go to 'results'
2. Select a 'benchmark'
3. Select all results (all button)
4. Plot a graph
5. Change the selected 'benchmark'

**Expected behavior**
After changing the selected benchmark:
 - The results should start as "deselected"
 - The graph should be reset
 - When selecting results, the graph should update 

**Additional context**
```
xhr.js:177 GET https://performance.services.fedcloud.eu/api/v1/users/self 401
(anonymous) @ xhr.js:177
e.exports @ xhr.js:13
e.exports @ dispatchRequest.js:50
Promise.then (async)
l.request @ Axios.js:61
r.forEach.l.<computed> @ Axios.js:76
(anonymous) @ bind.js:9
G @ api-helpers.ts:15
(anonymous) @ App.tsx:141
fetchFn @ query.js:264
c @ retryer.js:90
u @ retryer.js:150
t.fetch @ query.js:295
n.executeFetch @ queryObserver.js:186
n.fetch @ queryObserver.js:175
n.refetch @ queryObserver.js:159
t.onFocus @ query.js:141
(anonymous) @ queryCache.js:130
(anonymous) @ queryCache.js:129
t.batch @ notifyManager.js:22
n.onFocus @ queryCache.js:128
(anonymous) @ queryClient.js:33
(anonymous) @ focusManager.js:46
n.onFocus @ focusManager.js:45
(anonymous) @ focusManager.js:31
t @ focusManager.js:69
query.js:321 Error: Request failed with status code 401
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest._.onreadystatechange (xhr.js:62)
```

**Comment by TheChristophe** [comment]
Can you deselect if you switch back to the previous benchmark?
