### ISSUE TITLE
Merge folders "script" and "help_scripts"

### ISSUE THREAD

**Issue by BorjaEst** [EOSC-synergy/eosc-perf#145]
**Is your feature request related to a problem? Please describe.**
Folders "script" and "help_scripts" have the same purpose.

**Comment by BorjaEst** [comment]
@TheChristophe, can you do this? I am not sure if I change it how it will impact your environment.

**Comment by TheChristophe** [comment]
Done in e95566ade703b7846f3e2c0962c17049185e71a0
