### ISSUE TITLE
Add tests for DatabaseFacade

### ISSUE THREAD

**Issue by TheChristophe** [EOSC-synergy/eosc-perf#17]
To be tested:
- [x] Adding items
- [x] Adding duplicate items
- [x] Finding items

**Comment by TheChristophe** [comment]
Adding valid and invalid items including duplicate items is now tested.

**Comment by TheChristophe** [comment]
Tests should now cover all of facade operations except:
 - query_results (I'll leave this to @darkphoenix),
 - code that needs a result to check something,
 - code that needs a report to check something

**Comment by darkphoenix** [comment]
query_results is now completely covered
