### ISSUE TITLE
Make oidc redirect_uri hostname configurable

### ISSUE THREAD

**Issue by TheChristophe** [EOSC-synergy/eosc-perf#19]
This is currently hardcoded to localhost
See https://github.com/EOSC-synergy/eosc-perf/blob/master/app/controller/authenticator.py#L58
This should have an entry in config.yaml

**Comment by mlbehr** [comment]
Fixed in 5b728da95289e9dfe668906ecf45e92026a92fd4.

**Comment by BorjaEst** [comment]
Suppose it means the 'oidc_redirect_hostname'. The [redirect_uri](https://github.com/EOSC-synergy/eosc-perf/blob/master/app/controller/authenticator.py#L63) does not look configurable, (however it is not needed).
I would change the name of the issue.
