### ISSUE TITLE
Description are marked both as nullable and optional in the api spec

### ISSUE THREAD

**Issue by TheChristophe** [EOSC-synergy/eosc-perf#206]
**Describe the bug**
Fields Benchmark.description, CreateBenchmark.description, CreateFlavor.description, CreateSite.description, CreateTag.description, Flavor.description, Site.description, Tag.description are marked as both nullable (can have value or null) and optional (can be present or not present).
Optional is unnecessary, as it means that the field could be missing from the response, whereas it should always be included.

**To Reproduce**
1. Look at generated spec at /api/v1

**Expected behavior**
Fields are only marked nullable

**Comment by BorjaEst** [comment]
Well "CreateX.description" is a schema to be used only by POST methods and the user can omit them (so it is optional right?).
For the "X.description", I should remove nullable right?

**Comment by TheChristophe** [comment]
Yes, optional means field can be omitted (missing value), nullable means field must be there, but can be null (explicit no value). I believe for Create, it makes sense to have it optional, and for server responses, have it be nullable, but in general, it should be avoided having a field be both.

**Comment by BorjaEst** [comment]
From https://stackoverflow.com/questions/63192172/whats-the-best-way-to-handle-optional-field-in-put-http-request-at-backend
*If I do a PUT and then a GET of the same resource, the representation I receive from the GET should be equivalent to representation sent in the PUT.*

According to what I have read on API specs, GET should have same behaviour as PUT. It means I should remove nullable from "X.description" to make it reliable (as I never return nulleable, just omit description).

For "CreateX.description", CreateX are parent of X, so the "description" is inherited. Changing that behaviour would make the "CreateX.description" also optional (no nullable).

Would this fill you requirements?

**Comment by BorjaEst** [comment]
#220

**Comment by TheChristophe** [comment]
Yes, just optional is fine
