### ISSUE TITLE
Documentation/structure valid JSON

### ISSUE THREAD

**Issue by BorjaEst** [EOSC-synergy/eosc-perf#21]
Hi,

## Page: 
Upload Result; https://193.144.46.238/upload

## Issue description:
I tired to upload my fist file, but I was not sure what exactly to upload, I could not find any information about the structure the JSON should have.

## Expected:
Have a help command/link about where I can find the required JSON structure needed for each benchmark selection.

## Optional:
After I uploaded, the page returned me an error:
![image](https://user-images.githubusercontent.com/47473455/90512765-edbd4100-e15e-11ea-9ea6-52a677bf94e1.png)

It would be nice to have a tip about where is the mistake

**Comment by TheChristophe** [comment]
Do we have any kind of specific prescribed structure, or structure you'd like us to use? Currently we're referencing the example provided to us by Valentin by email a few months ago (see https://github.com/EOSC-synergy/eosc-perf/blob/master/app/controller/config/result_template.json).
Currently the JSONValidator checks if the entire json data-tree/all keys match the example json, but a lot of it seems like extra noise. Currently the only used fields are user_args.num_gpus and evaluation.result.average_examples_per_sec in the diagram page, so unless you want us to require anything else, I believe these are the only fields we'd require (e.g. what will be written in the help text).

**Comment by BorjaEst** [comment]
That is good, I see you have simplified it a lot.

> Is it configurable on the code? 
> Would it be difficult to do so?

In some cases I undestand not all the fields are mandatory, for example a computer might not have any GPU. It would be nice display in this area what are you matchin in the controller to verify if the file is correct: 

![image](https://user-images.githubusercontent.com/47473455/90779651-5db5fd80-e2fe-11ea-9978-4fac9de3a96d.png)

That way I could see which fields are optional and what is failing in my .json.

I see there is a field "Select benchmark". I suppose this is the type of ".json" that would match.
(Correct me if I am wrong)

Is therefore "Add benchmark" to create new types of accepted ".json" to be comparede later?

**Comment by TheChristophe** [comment]
> I see there is a field "Select benchmark". I suppose this is the type of ".json" that would match.
(Correct me if I am wrong)

>Is therefore "Add benchmark" to create new types of accepted ".json" to be comparede later?

Currently there is only one global template used for every submitted result. We could change it so it uses a template that is stored with the benchmark info, then the user would have to submit a template when adding a new benchmark, along with what fields to use for the speedup graph.

**Comment by vykozlov** [comment]
In general, yes, there can be different benchmarks with completely different fields. For example, if one tests I/O of a system, it is very different from testing GPU performance. Therefore:
1) test that uploaded document is JSON (must)
2) check that in the uploaded document, necessary fields are present -> depends on a particular benchmark.

Now, for very first testing, we may relax requirements to only 1), i.e. that it is JSON.

**Comment by vykozlov** [comment]
Next, is 2) : that **necessary** fields are present. It should **not** be the exact match! 
For instance, example I sent by email, does not pass your current check and rejected with the same "Failed to submit result: no valid result JSON"

**Comment by vykozlov** [comment]
OK, maybe it failed because my document did not have "_evaluation.average_examples_per_sec_" but "_training.result.average_examples_per_sec_", which is in fact, **more important** :-)

**Comment by TheChristophe** [comment]
> 
> 
> OK, maybe it failed because my document did not have "_evaluation.average_examples_per_sec_" but "_training.result.average_examples_per_sec_", which is in fact, **more important** :-)

Sorry, when I flew through it for what parameters to use, I just assumed the training section was just input parameters, and the end result was in evaluation, totally missing that there's two seperate average_examples_per_sec. 🤔

>     2. check that in the uploaded document, necessary fields are present -> depends on a particular benchmark.

We can of course make the template field for new benchmarks optional. Same thing for the speedup fields; however if the field is empty, speedup graph will be unavailable for that kind of benchmark.

> **Update**: no, tried another document with "evaluation.result.average_examples_per_sec", still "Failed to submit result: no valid result JSON"

I do believe the validator checks if the set of keys is exactly the same, not a subset, so that's a bug I'll file seperately.

**Comment by uceul** [comment]
Since 4f52fdd the uploaded result must not have the exact same keys as the template. The keys in the template must only be a subset of the uploaded result's keys. I'll work on more informative error messages during the next week.

**Comment by mlbehr** [comment]
Since 4f52fdd the uploaded result's keys must only be a subset of the template's keys. I'll work on more informative error messages during the next week.

**Comment by mlbehr** [comment]
Since 867a5f0 the missing key that made the upload fail is included in the error message.

**Comment by BorjaEst** [comment]
I am still getting the error:
Failed to submit result: Uploaded Json misses the following (sub-)keys: {'num_gpus'}

Even if the field "" is set.

Is it mandatory to have always the field 'num_gpus'? Or depends on the selected benchmark? I am using "someone/cpu_pi" which in theory should not be GPU but CPU dependent.

**Comment by TheChristophe** [comment]
The num_gpus key must be a sub-key of 'training' (https://github.com/EOSC-synergy/eosc-perf/blob/master/app/controller/config/result_template.json#L6), I think the full path to the missing key should be displayed if it's missing as to not cause confusion.

Currently, following the template, there must always be a num_gpus field, and this is what the speedup chart uses. Given the diagram only reads out a 'core_count' and 'score', we could, however, add a 'x-field' and a 'y-field' to the benchmark entry to specify what field should be used for the diagrams (if any), which would define the fields to be used for the chart axes.

**Comment by TheChristophe** [comment]
We should now have an error message that documents which keys are missing. Do we intend to add a visible example of the required keys to the upload page, or do we think the error message is sufficient? @mlbehr

**Comment by mlbehr** [comment]
I think for real world usage an error message is sufficient. Normally you would upload a real benchmark result which should contain all required fields. If one is missing, something went wrong, so I think an error message suffices.

**Comment by TheChristophe** [comment]
That does sound reasonable. I think if you're trying to upload random jsons and fill in random fields you're doing something wrong. Given real results come out of benchmarks however, I think such an example should be given to the code guidelines page, so that developers creating new benchmarks know what to output (#39). I'll mention it in the other issue and close this one for now.
