### ISSUE TITLE
User is not informed when logged out

### ISSUE THREAD

**Issue by BorjaEst** [EOSC-synergy/eosc-perf#22]
## Page: 
Any

## Issue:
User is not informed when the session expires.
It is a bit annoying when you have entered all the data, you click on the button and all is lost...
Also some other issues like #20 related here.

## Expected:
- The user gets and alert (or similar) when the session expires or the token is not longer valid.
- Extend the duration of the session longer (actually I think it is only 5 min aprox)
- Ensure that the session is refreshed at each click

## Notes / Additional:
- Optional: Data is not lost if the token expires during the session.

**Comment by TheChristophe** [comment]
Related: #14

**Comment by mlbehr** [comment]
The user will now stay logged in as long as the refresh token stays valid which is at least 14 days (or he logs out). I don't think there needs to be an alert because if a user stays inactive for 14 days, it should not be a surprise that they get logged out. So I'll close this for now.
