### ISSUE TITLE
Tag deletion

### ISSUE THREAD

**Issue by BorjaEst** [EOSC-synergy/eosc-perf#23]
Thinking about if there should be an option to delete Tags.
What would happend if users start creating a lot of tags?
The list of tags would be huge.

Regarding
> In case I do a mistake and I add a worng tag, will it be on the display list forever?

It may be reasonable to only add the newly added tags if they were selected for the result? CC: @mlbehr

_Originally posted by @TheChristophe in https://github.com/EOSC-synergy/eosc-perf/issues/20#issuecomment-676843444_

Another solution could be like other webpages do (Github, etc)
Have infinite tags but only display the most used and use autocomplete for the rest.

**Comment by vykozlov** [comment]
Remember, "Add new tag" is a functional requirement in the "Requirements" document, marked as "optional", i.e. not the highest priority. 

More general question:  are there some kind of permissions set for every user upload? I mean, like in many cases: I created a document/file/folder, it is only me and the administrator who can modify it, others can view. If so, a user can modify/edit/delete his/her uploads, tags etc. If not, then asking for e.g. "delete tag", would mean any user can delete any tag?

**Comment by TheChristophe** [comment]
> If so, a user can modify/edit/delete his/her uploads, tags etc. If not, then asking for e.g. "delete tag", would mean any user can delete any tag?

Tags (currently) do not carry author/creator/ownership information, so were there be a tag deletion function, only admins would be able to use it.

Things that **do** carry info about their creator: results, reports, benchmarks
Things that **do not**: tags, sites

**Comment by BorjaEst** [comment]
What is the expected behaviour in case the are 100 of tags?
It might be complicated for the user to select the needed in a very long list.

**Comment by mlbehr** [comment]
I opened a new issue for a more user friendly tag selection: #31

**Comment by TheChristophe** [comment]
I propose the following alternative: folding this into #40, and tying the lifetime of a tag to the results it's associated to. This means that you can only 'add' a tag if you also associate it to a result, and once all results associated to a tag are removed, the tag is also removed. As a result, you can add tags on the result submission page and on the result (tag) edit page, and remove the tags by disassociating them from their results or deleting all those results.

If you object to this approach, please reopen the issue.
