### ISSUE TITLE
Choose testing framework

### ISSUE THREAD

**Issue by TheChristophe** [EOSC-synergy/eosc-perf#25]
Currently no testing framework has been determined for usage. This must be done so tests can be written. Before this is done, issues such as #17 cannot progress.

**Comment by vykozlov** [comment]
We use 'unittest' in some of our projects, e.g. [1-2], in others 'testtools', e.g. [3].

To run tests: stestr [4] but pytest can be used as well. For more advanced scenarios: tox tool [5] to run e.g. unit tests, style tests, security tests based on the 'bandit' tool [6] (for examples, [2-3]).

You can certainly start with "unittest" + stestr (or pytest). Tox can be added later but in many cases, you may just copy/paste tox.ini from [2-3] and adjust it accordingly. 

While testing, you may need more python packages, which you do not require for running the software. The convention used:

- requirements.txt - necessary for your software python packages;

- test-requirements.txt - additional python packages needed for testing.

[1] https://github.com/indigo-dc/flaat/tree/master/tests ,
[2] https://github.com/deephdc/dogs_breed_det/tree/master/dogs_breed_det/tests
[3] https://github.com/EOSC-synergy/DEEPaaS/tree/eosc-synergy/deepaas/tests
[4] https://stestr.readthedocs.io/
[5] https://tox.readthedocs.io/en/latest/
[6] https://pypi.org/project/bandit/

**Comment by mlbehr** [comment]
Thanks for the overview :). For now we are going to stick with unittest and see if we can implement all necessary tests with that.
