### ISSUE TITLE
Create privacy policy

### ISSUE THREAD

**Issue by TheChristophe** [EOSC-synergy/eosc-perf#26]
We should have a privacy policy (page), because we handle people's data. This will be linked in #12.
A starting point is something like https://docs.google.com/document/d/1ZU7VjH3g7qcfWcz0Z8TTv-vQiVoRA_wOsuMyJaz28Og/edit, as referenced by Marcus during the last colloquium.

**Comment by darkphoenix** [comment]
Draft policy added, please review
