### ISSUE TITLE
Search page: tag cloud, list all available results

### ISSUE THREAD

**Issue by vykozlov** [EOSC-synergy/eosc-perf#27]
**Is your feature request related to a problem? Please describe.**
When now going to "Search" page, I have no idea, what I can search. For instance "karlsruhe" does not yield anything. 
What fields are searched, tags, locations, uploaders, ...?

**Describe the solution you'd like**
A search should go over different fields (benchmark name, locations, uploaders, etc).

It would be nice to have a page which would list all available results, separated in "sub-pages" (i.e. 10 most recent results shown, to see more click "next" or "page 2"). In principle, this is search results with no parameters, i.e. everything is shown.

As an addition, one could show a TagCloud, i.e. all tags with the size of letters depending on the frequency of the tag usage.

**Comment by Falkenberg-Marc** [comment]
In the Info field of the tag filter, the distribution of tags among the loaded results is shown.

**Comment by TheChristophe** [comment]
Is this issue still relevant?

**Comment by vykozlov** [comment]
move tagcloud to a separate issue, otherwise can close :-)
