### ISSUE TITLE
Added tags: reset after restart

### ISSUE THREAD

**Issue by vykozlov** [EOSC-synergy/eosc-perf#29]
**Describe the bug**
It seems, that added by a user tags are reset after restart of the container.

**To Reproduce**
1. During "Upload Result" create a new tag, e.g. "V100"
2. Submit new result
3. Restart the container of eosc-perf
4. Check if "V100" tag is still available

**Expected behavior**
Tags survive restart and rebuild of the container.

**Comment by TheChristophe** [comment]
The commit added a way to configure the database reset and I tested the database not removing a newly added tag. Please reopen if the test fails for you.
