### ISSUE TITLE
Improve Tag Selection

### ISSUE THREAD

**Issue by mlbehr** [EOSC-synergy/eosc-perf#31]
**Is your feature request related to a problem? Please describe.**
Selecting tags during result upload can be tedious when the tag list becomes longer.

**Describe the solution you'd like**
- Alphabetically sorted tag list
- Improve selection mechanism by turning list elements (tags) into checkboxes
- Some kind of filter mechanism for the tag list

**Comment by mlbehr** [comment]
Since eedf272 the tag list is sorted alphabetically.

**Comment by mlbehr** [comment]
Due to time constraints and this being a rather low-priority enhancement, I was only able to implement the first task (alphabetically sorted tag list). 

For anyone who wants to implement the remaining tasks: the tag list is created here https://github.com/EOSC-synergy/eosc-perf/blob/d1a4dee228d01a40838543530b4f52b5da6c14a6/templates/upload.html#L53-L55 and filled here: https://github.com/EOSC-synergy/eosc-perf/blob/c57b7a95e220db46d52666fc80ef41a7242ea29e/static/scripts/view/upload.js#L165-L176

**Comment by TheChristophe** [comment]
The multi-selection system has been improved as of 04fb3b2f508e6dc2761040cadc1bec841dc614be. I will open a separate issue for tag search.
