### ISSUE TITLE
Sort order on the search page

### ISSUE THREAD

**Issue by BorjaEst** [EOSC-synergy/eosc-perf#32]
To be decided

**Comment by BorjaEst** [comment]
To be decided

**Comment by BorjaEst** [comment]
There are 2 points to be considered here:
- Usage (from user point of view): The user, needs some flexibility to interact with the graphs and results (changing the order) as the order plotted/listed by the tool might not be the best.
For example, acording to the description it is important to sort acording to "GPU type, neural network type or dataset"

- Testing: Acording to the specs, it should be possible to test the results provided are sorted correctly.

How to do it simple?
### Proposal:  
I see you are able to filter by internal values (for example: user_args.num_gpus). Probaly it should not be complicated to add an external button (+Add sorting) which would indicate the sorting of the list.
For example (Sort descending by value: user_args.num_gpus).
> Note, the plot after should be also folowing the sorting rules. 

That would make user sort customization at plots and at listing.
(and probably also testing)

### How to test:
Who is filtering/sorting? The Frontend or the Backend?
- Backend: Simple, just add the sort request to the query.
- Frontend: *Depends on how are you planning to test the filters.

**Comment by darkphoenix** [comment]
Suggested implementation:
Click "Data" -> a text field for entering a JSON template is displayed, the template is verified and if it matches the column title changes to "Data (sorting by a.b.c)".

**Comment by TheChristophe** [comment]
Closing this as this should be covered by the current notable fields sorting.

**Comment by BorjaEst** [comment]
On the new version it is not possible to sort.

The user would like to sort by site, flavor and tag.
Currently the backend only supports sort by id, but that is not useful.

**Comment by BorjaEst** [comment]
Sort at the backend is not possible.
It is needed to add this function to the frontend again.

**Comment by TheChristophe** [comment]
Miscommunication resolved, a "now" was a "not".

**Comment by BorjaEst** [comment]
Issue with backend sorting solved #148 
Now it should be possible to continue
