### ISSUE TITLE
Unittests for Controller Classes

### ISSUE THREAD

**Issue by mlbehr** [EOSC-synergy/eosc-perf#35]
We need unit tests written with the unittest package for some classes of the controller:

- [x]  IOController
- [ ]  JSONResultValidator

**Comment by BorjaEst** [comment]
To run all test at the same time see:
https://docs.python.org/2/library/unittest.html

Basically you have to rename all test files with some pattern (normally "*_test.py") and run:
```py
python -m unittest discover -p "*_test.py"
```

**Comment by mlbehr** [comment]
IOController unit tests are (apart from the _valid_docker_hub_name method) done since 3da8da4. I will add an additional unit test for the _valid_docker_hub_name method as soon as #34 is done.

**Comment by mlbehr** [comment]
Since 36b787a JSONResultValidator and IOController have 100 % test coverage.
