### ISSUE TITLE
Document tag usage

### ISSUE THREAD

**Issue by BorjaEst** [EOSC-synergy/eosc-perf#36]
**Describe the bug**
When filtering by a result value (for example "num_gpus") the result list is empty.

**To Reproduce**
1. Go to "Result Search"
2. Set filter "Value greater than";"num_gpus";2
3. Click on "Find Results"

**Expected behavior**
See the results which meet the selected filter criteria.

**Screenshots**
This screenshot shows the results using the described filter:
![image](https://user-images.githubusercontent.com/47473455/92358010-0fb83c80-f0e9-11ea-9f65-e5e0e23d8e7a.png)

However, there are some results which meet the criteria:
![image](https://user-images.githubusercontent.com/47473455/92358020-1646b400-f0e9-11ea-89a5-a00fbe3f2235.png)

**Additional context**
Not sure about how it is exactly working this type of filter, but is should work on the evaluation results so it is useful to the user.

**Comment by TheChristophe** [comment]
The example provided is using incorrect syntax; you need to use the full path to the variable (notably 'user_args.num_gpus' in this case) because a single key may be ambiguous.

**Comment by BorjaEst** [comment]
Working, however:
It should be improve in the documentation/page-tips before closing.

**Comment by Falkenberg-Marc** [comment]
A Information field describing the expected format for each filter was added.
