### ISSUE TITLE
Select all button on "Result Search"

### ISSUE THREAD

**Issue by BorjaEst** [EOSC-synergy/eosc-perf#37]
**Is your feature request related to a problem? Please describe.**
It is a bit anoying to click all results one by one after you filter, and it might become a biger problem once we expect big list of results.

**Describe the solution you'd like**
A button select all on "Result Search" would select all the filtered values on the result search.

**Comment by Falkenberg-Marc** [comment]
A button inverting the selction got added. can be used to slect all results or exclude spcific results more intuitivly.
