### ISSUE TITLE
Add benchmark fails without providing information 

### ISSUE THREAD

**Issue by BorjaEst** [EOSC-synergy/eosc-perf#38]
**Describe the bug**
After submit benchmark, error message raises, but there is no description about the error reason (and how to solve it)

**To Reproduce**
1. Go to 'Add benchmark'
2. Fill the forms
3. Click on 'Submit benchmark'

**Expected behavior**
Get information about what failed: Form error? Server error?

**Screenshots**
When submitting the new benchmark details:
![image](https://user-images.githubusercontent.com/47473455/92361560-d5519e00-f0ee-11ea-81b3-7e4fe0168254.png)

This is the Error message received:
![image](https://user-images.githubusercontent.com/47473455/92361480-b521df00-f0ee-11ea-9fd0-7358e81cc221.png)

**Comment by TheChristophe** [comment]
I am not entirely certain how the Controller's existence check works, but I believe the submission fails because it is not a legitimate docker name (e.g., there is no such image on docker hub).

**Comment by BorjaEst** [comment]
I tested it with an existing image: "synergyimk/o3skim:latest", but it returns the same error.

In any case, the error message should return something like:
 -  Image not found at .....
 - Image missing some fileds?
 - Internal server failure (contact the developers or similar)
 - etc.

**Comment by TheChristophe** [comment]
> I tested it with an existing image: "synergyimk/o3skim:latest", but it returns the same error.

I can confirm this. Just to mention it, I believe this is related to a seperate issue (#34) because the check method doesn't seem to accept certain valid names (as example, any names including tags).

**Comment by mlbehr** [comment]
I made the erorr messages more informative (, but issue #34 remains and most docker names are still not valid, even though they should be.
