### ISSUE TITLE
Add code guidelines page

### ISSUE THREAD

**Issue by darkphoenix** [EOSC-synergy/eosc-perf#39]
The software should have a code guidelines page.

This page should be implemented by pulling in the actual guidelines from a text file provided by the user.

**Comment by TheChristophe** [comment]
The code guidelines should include an example output json file/structure the system expects to receive.

**Comment by darkphoenix** [comment]
Is this resolved by 13eeedf?

**Comment by Falkenberg-Marc** [comment]
A dummy page displaying the minimum requirements for the json output file was added. 
Still might be nessercary to add further guidelines or remove the "dummy" headline.
