### ISSUE TITLE
Edit tags of result

### ISSUE THREAD

**Issue by mlbehr** [EOSC-synergy/eosc-perf#40]
On the result info pages there should be functionality for adding or removing tags.
Only the uploader and admins should have access to this functionality.

**Comment by mlbehr** [comment]
Because of time constraints I won't be able to implement this. But I will give my thoughts on the implementation of the feature if anyone wants to implement in the future.

- The result display page is here: https://github.com/EOSC-synergy/eosc-perf/blob/master/templates/display_json.html but there is no .js for it yet. One would need to create one.

- The .js file would need to get the result object through a ajax query. The uuid of the result can be found in the url. The uuid should be used as a filter to only find the viewed result through the query. A similar query is used here: https://github.com/EOSC-synergy/eosc-perf/blob/8a87fca3c24d30a31c66b334658fde6ecd2fecbe/static/scripts/view/search_results.js#L248-L262

- Using the result object, one could show a list of all associated tags to the user. The user then must be able to select an associated tag and click a remove button, which would remove the associated tag from the result. 

- One would also need a list of all not associated tags. This can be done by getting a list of all tags using an ajax query similar to this one: https://github.com/EOSC-synergy/eosc-perf/blob/8a87fca3c24d30a31c66b334658fde6ecd2fecbe/static/scripts/view/upload.js#L168-L175 and then removing all tags that are associated with the result. This list must be displayed to the user. The user must then be able to select a not associated tag and click a "add tag" button which adds this tag to the result.

**Comment by TheChristophe** [comment]
Reiterating the suggested change in #23, tags are now tied to the results they are associated to. Tags should only get added if they are also used. Once the tag is removed from any results (or, equivalent, all results associated to the tag are deleted), the tag gets deleted.

**Comment by TheChristophe** [comment]
Implemented in a2e7e84d9abc2354a6c7bb577a8f5157a92a91cf
