### ISSUE TITLE
Can't remove results

### ISSUE THREAD

**Issue by vykozlov** [EOSC-synergy/eosc-perf#45]
**Describe the bug**
Logged in, Select Result, use either "Delete Result" or "Report" and then "Remove result" as admin, does *not* remove the result.

**To Reproduce**
1. https://193.144.46.238/result_search
2. Filter: Benchmarks "someone/benchmarks"
3. Go to page 6, find 
someone/benchmarks | paris | email | ...
4. Click "Delete Result" button -> The method is not allowed for the requested URL.
5. Click "Report", provide reason, e.g. "duplicate of IFCA-LCG2 results", Submit (successful)
6. Goto "Admin menu", select "Review first result report"
7. Find the report
8. Click "Remove result" red button (page bottom)
9. Goto the search page again, complete steps 1.-3. above, the result is still there, i.e *not* removed.

**Expected behavior**
Result is removed.

**Comment by TheChristophe** [comment]
> Click "Delete Result" button -> The method is not allowed for the requested URL.

It seems it's calling report result with a POST, which is not accepted. Why the delete button is calling the report end point (e.g. the same point as the report button) in the first place, I don't know. Please advise @Falkenberg-Marc 

> Click "Report", provide reason, e.g. "duplicate of IFCA-LCG2 results", Submit (successful)
Goto "Admin menu", select "Review first result report"
Find the report
Click "Remove result" red button (page bottom)
Goto the search page again, complete steps 1.-3. above, the result is still there, i.e not removed.

For this, my assumption is that the result properly gets marked as hidden, but that the ResultFilterer does not check for hidden results and just returns them all. Please advise @darkphoenix

**Comment by darkphoenix** [comment]
Hidden-ness is indeed not considered, will fix when I get home.

**Comment by TheChristophe** [comment]
I have checked, the delete button issue seems to be related to #13. Any progress on #13? @Falkenberg-Marc

**Comment by darkphoenix** [comment]
My part of this bug should be resolved now.

**Comment by mlbehr** [comment]
> I have checked, the delete button issue seems to be related to #13. Any progress on #13? @Falkenberg-Marc

I moved @Falkenberg-Marc 's part of #13 to #34. Just wanted to mention that to avoid confusion.

**Comment by TheChristophe** [comment]
> I moved @Falkenberg-Marc 's part of #13 to #34. Just wanted to mention that to avoid confusion.

Oh, I actually meant #16 , sorry. Forgot the issue number inbetween pages.

**Comment by Falkenberg-Marc** [comment]
Should work now.
