### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by vykozlov** [EOSC-synergy/eosc-perf#46]
**Is your feature request related to a problem? Please describe.**
T2.8 metions as Reaction:
The system generates plots comparing various datapoints, such as the resulting benchmark numbers against the number of
GPUs or the chosen site. Verified by F2.

F2: Users must be able to visualize benchmark results by generating speedup graphs and performance comparison graphs.

Speedup graphs are now produced by selecting several results and clicking "Visualize" button. However, there is no possibility to 
compare performance of different sites (directly).

**Describe the solution you'd like**
a) There is something like "Compare performance vs. <selectable list>" <Selectable list> is a list of possible parameters (taken from a certain config?), e.g. "date", "num_gpus", "site". Once the parameter is selected, for instance, num_gpus or site, either speedup plot or performance comparison for different sites is plotted.

b) Have two separate buttons "Visualize" and "Compare sites" for performance comparison vs. num_gpus or vs. different sites.

a) is a bit more preferred, as it may allow to add more parameters for visualization (for example, if we expand to GPU type, we may build a plot performance vs. GPU type).

Priority for now: what is easier and faster to implement and test.

**Comment by TheChristophe** [comment]
I can change the diagram generation page to be configurable by input as to which json data it should use to plot the graph, so a) is possible to achieve. The rest would have to be done in the search UI by @Falkenberg-Marc . Let me know which option you want to go with @Falkenberg-Marc .

**Comment by TheChristophe** [comment]
Due to a lack of a response from @Falkenberg-Marc and a suggested alternative in the meeting, I have decided to implement an alternative suggested by Jonas or Valentin (I don't remember) in the meeting, to just keep the diagram mostly as-is, but to display site names under the graph points if comparing multiple sites. This has been implemented in a7fd1d03.
