### ISSUE TITLE
Results pagination isn't reset when hitting "Find Results"

### ISSUE THREAD

**Issue by darkphoenix** [EOSC-synergy/eosc-perf#48]
**Describe the bug**
When selecting a page, then changing filters, the page number is not reset, resulting in either the wrong page or no results at all being shown

**To Reproduce**
1. Go to ResultSearch
2. Go to Page 8
3. Add a filter, like "someone/gpu_cuda"
4. See no results, because there are less than 8 pages or results
5. Remove filter, go to page 5
6. Add filter again
7. See page 5 of results for gpu_cuda, while still having the dropdown show "Page: 1"

**Expected behavior**
The page properly tracks pages and resets to page 1 when filters are changed.

**Comment by Falkenberg-Marc** [comment]
should update the pages on the search now.
