### ISSUE TITLE
Number of results per search page is not consistent

### ISSUE THREAD

**Issue by TheChristophe** [EOSC-synergy/eosc-perf#49]
**Describe the bug**
While navigating search results, the number of results per page may randomly change.

**To Reproduce**
1. Go to the search page
2. Filter the query in a way to have multiple pages (test data example: benchmark = someone/benchmarks)
3. Set it to view 100 results
4. Set it to view 10 results
5. Navigate to page 2

**Expected behavior**
The list shows 10 results.

**Screenshots**
The list shows more than 10 results.

**Additional context**
n/a

**Comment by Falkenberg-Marc** [comment]
JavaScript typing is awesome, add tow integers wich string addition and interpret the result as an integer, anyway should be fixed now.
