### ISSUE TITLE
HTTP should redirect to HTTPS

### ISSUE THREAD

**Issue by BorjaEst** [EOSC-synergy/eosc-perf#50]
**Describe the bug**
When you enter http, a "Welcome to nginx!" is displayed.

**To Reproduce**
1. Go to 'http://perf.test.fedcloud.eu'

**Expected behavior**
301 Redirect to https.

**Additional context**
See 'https://serversforhackers.com/c/redirect-http-to-https-nginx'

**Comment by TheChristophe** [comment]
The "Welcome to nginx!" page us unrelated to our application, someone launched a seperate nginx server.
The app is currently configured to expose HTTP to :8080, which normal browsers do not try, so your browser would try :443/HTTPS anyway.

**Comment by BorjaEst** [comment]
That is right... probably it was installed by certbot when trying to introduce the certificates.
So I have uninstalled nginx.

At this point, certbot needs to check the domain is "ours" to update the certificates. That means, that to work correctly it needs to expose "something" at http (port 80). In any case I think that is out of the requirements, so I will updated it myself so it works properly.

For your interest, I have changed the following and it works:

Expose at 80 (modifying the following line to 80:80):
https://github.com/EOSC-synergy/eosc-perf/blob/74d8fe85d2be5a9018845150cbba8c6adaa5a990/docker-compose.yaml#L19-L24

Introduce a new server that redirects 80 to 443 in nginx configuration:
```conf
...
server {
  listen       80 default_server;
  listen       [::]:80 default_server;
  server_name _;
  return 301 https://perf.test.fedcloud.eu;
}
...
```

**Comment by BorjaEst** [comment]
I will better create a PR to keep it on track

**Comment by TheChristophe** [comment]
You may also want a special rule for certbot's check folders in the :80 server setting, so you can set up a system where it can renew the certificates automatically

```
location /.well-known/acme-challenge/ {
  root /var/www/certbot;
}
```

**Comment by BorjaEst** [comment]
> You may also want a special rule for certbot's check folders in the :80 server setting, so you can set up a system where it can renew the certificates automatically
> 
> ```
> location /.well-known/acme-challenge/ {
>   root /var/www/certbot;
> }
> ```

Probably we will need it as well thanks.
But I am not getting the details nor more time today.

let's keep the issue/PR open so I will integrate it before close it after the presentation.
Cheers!
