### ISSUE TITLE
Move to production

### ISSUE THREAD

**Issue by BorjaEst** [EOSC-synergy/eosc-perf#54]
You would have to change this line:
https://github.com/EOSC-synergy/eosc-perf/blob/74d8fe85d2be5a9018845150cbba8c6adaa5a990/app/controller/authenticator.py#L19

By this:
```py
CONF_URL = 'https://aai.egi.eu/oidc/.well-known/openid-configuration'
```

**Comment by TheChristophe** [comment]
This should now be configurable by turning debug on or off. See 7d571918eab7b69b213a7291e14af939f9dced75

**Comment by mlbehr** [comment]
As the service is now running in production, I think I can close this.
