### ISSUE TITLE
Create developer instructions.

### ISSUE THREAD

**Issue by BorjaEst** [EOSC-synergy/eosc-perf#57]
It would be nice to have some instructions about how to do a dev installation. That way it  would be easy to help you. For example:

- [ ] How to install locally (without docker, I recommend setup, to be open in other issue)
- [x] How to run the unit tests (I would recommend to use tox, probably in other issue)

**Comment by TheChristophe** [comment]
To run the unit tests, you can
 - setup a venv `python -m venv venv`,
 - enable it `. ./venv/bin/activate`, 
 - install all requirements `pip install -r requirements.txt`,
 - run the command listed at the bottom of the README.md `python -m unittest discover eosc_perf "*_test.py"`

I'll add the venv/pip instructions to the README.md.

**Comment by TheChristophe** [comment]
I have now added instructions on how to run the tests into the README.md. If we want to migrate running tests to tox, we should create another issue about it.

**Comment by BorjaEst** [comment]
I can take the start for that.
I run the software and some of the test failed. We can review it on the next meeting and open another issue if needed.

**Comment by BorjaEst** [comment]
I created a new PR #67, to implement tox. It is quite stable for now and provide test results.
We should review it together before merge it.
