### ISSUE TITLE
Service eosc-perf_nginx_1 dies due to file inconsistency

### ISSUE THREAD

**Issue by BorjaEst** [EOSC-synergy/eosc-perf#61]
**Describe the bug**
When deploying I usign docker compose I get the following error:
```
$ docker-compose up
...
nginx_1    | 2020/11/23 13:50:56 [emerg] 1#1: open() "/etc/letsencrypt/options-ssl-nginx.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/app.conf:29
nginx_1    | nginx: [emerg] open() "/etc/letsencrypt/options-ssl-nginx.conf" failed (2: No such file or directory) in /etc/nginx/conf.d/app.conf:29
...
eosc-perf_nginx_1 exited with code 1
```

**To Reproduce**
1. Download a fresh copy usng git clone (in a computer without certbot?).
2. Create a configuration file that should work.
3. Run `docker-compose up` on the repository.

**Expected behavior**
The service `eosc-perf_nginx_1` should be stable.

**Additional context**
Not sure where the issue might be.

**Comment by TheChristophe** [comment]
Have you done step 3 of the deploy instructions? The script(s) should downloads these files (= the recommended SSL settings from letsencrypt).

If you're developing locally (`localhost`), run `bash init-dev-certs.sh` which generates a certificate for local use. Currently to deploy it on a server with a domain, you may edit the domains=() list in init-letsencrypt, then run `bash init-lentsencrypt.sh` (but the domain is also hardcoded in a few other places, still, that should be changed too), which will request a letsencrypt cert for your domain.

**Comment by TheChristophe** [comment]
Is this resolved?

**Comment by BorjaEst** [comment]
Yes
