### ISSUE TITLE
Add custom site flavor submission

### ISSUE THREAD

**Issue by TheChristophe** [EOSC-synergy/eosc-perf#73]
**Is your feature request related to a problem? Please describe.**
Users do not have a way to describe execution environment if they have used a custom flavor until an admin is asked to edit the flavor.

**Describe the solution you'd like**
A field in the result upload page.

**Comment by vykozlov** [comment]
Judging from OpenStack (thanks to Viet and Miguel), Flavors in the OpenStack define the exact configuration of a VM. Normal users (via IM or other clients) cannot create new flavors with customized sizes, they must use existing flavors.
Therefore, there should not be a need for "custom site flavor submission".
