### ISSUE TITLE
Update the Privacy Policy

### ISSUE THREAD

**Issue by vykozlov** [EOSC-synergy/eosc-perf#81]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Update the Privacy Policy

**Comment by BorjaEst** [comment]
Points to be resolved:

- [ ] Data controller
- [ ] Jurisdiction and supervisory authority
- [ ] Contact information --> Create a list?
- [ ] Access, correction and deletion of data --> Contact information 
- [ ] Withdrawal of consent --> Contact information 
- [ ] Data retention --> Maximum time data is going to be stored (Backups delete policy?)

**Comment by BorjaEst** [comment]
Supervisory authorities (DPAs):


<ul>
<li><p><a href="https://www.bfdi.bund.de/DE/Home/home_node.html">German DPA</a>. Details for raising concerns for the German DPA can be found <a href="https://www.bfdi.bund.de/DE/Service/Datenschutzerklaerung/datenschutzerklaerung-node.html">here</a></p></li>
<li><p><a href="https://www.baden-wuerttemberg.datenschutz.de/">Baden-W&uumlrttemberg DPA</a>. <a href="https://www.baden-wuerttemberg.datenschutz.de/online-beschwerde/">Link</a> to file a complaint.</p></li>
</ul>

**Comment by BorjaEst** [comment]
Contact list:
- perf-support@lists.kit.edu

**Comment by BorjaEst** [comment]
Data retention:
As long as there are uploaded results from the user.
This is required to contact the uploader user in case of errors and issues

**Comment by BorjaEst** [comment]
Missing to detail when LOG data is deleted
