### ISSUE TITLE
Clicking on the "benchmark" does not immediately lists corresponding results

### ISSUE THREAD

**Issue by vykozlov** [EOSC-synergy/eosc-perf#84]
**Describe the bug**
Clicking on "benchmark" from the "Benchmark Search" page opens list of *all* results, not those related to the selected benchmark.

**To Reproduce**
1. Go to https://perf.test.fedcloud.eu/ -> Search -> Benchmark
2. Click on e.g. 'deephdc/deep-oc-benchmarks_cnn:synthetic'
3. The page "Result Search" opens but lists *all* results.

**Expected behavior**
It is expected that "Result Search" page immediately lists results corresponding to the selected benchmark.

**Comment by TheChristophe** [comment]
It was a timing issue: the page loaded results before the benchmark from the benchmark search was set, which only happens after the server sends back the list of benchmarks, so the page can select the benchmark in the dropdown of benchmarks.
