### ISSUE TITLE
Strange sorting by a column values in Chrome

### ISSUE THREAD

**Issue by vykozlov** [EOSC-synergy/eosc-perf#86]
**Describe the bug**
"Result search" table allows to sort data by certain columns, e.g. "num_gpus", score. The sorting is however different in Chrome and Firefox. Sorting in Chrome (version 87) seems to be incorrect, e.g. "1 2 4 8 1 4 2".

**To Reproduce**
1. Use Chrome web-browser. Used by me: Version 87.0.4280.88 (Official Build) (64-bit), English, Linux OS.
2. Go to https://perf.test.fedcloud.eu/result_search?benchmark=deephdc/deep-oc-benchmarks_cnn:synthetic
3. Scroll the table to see "num_gpus", click to sort.
4. See the order "1 2 4 8 1 4 2" (all data belong to the same Site but two "Flavours". "8 1 4 2" - belong to the same "Flavour").

**Expected behavior**
Firefox lists same data as "1 1 2 2 4 4 8", same system.
One may request additional feature to group results by a) Site b) Site + Flavour, e.g. "1 2 4 1 2 4 8"

**Screenshots**
Chrome:
![image](https://user-images.githubusercontent.com/8523545/108282951-c59cb200-7182-11eb-83c0-b3b9a8089b73.png)

**Comment by TheChristophe** [comment]
I seem to have confused the js array sort comparator with C++-like boolean comparators. I'm surprised firefox knew how to handle it, but chrome couldn't. I've tested it and it seems to work properly in chrome now.
